/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package squindex


import squindex.api.TestCaseViewResponse
import squindex.service.SquashService
import squindex.service.WrapperService

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        println new App().greeting
        // * T.N.R - Unified 7.33
        String topLevelTestFolder = "https://tools.akio.fr/squash/backend/test-case-folder-view/14527?frontEndErrorIsHandled=true"
        List<String> fetchedTestCaseFolderUrls;
        List<String> fetchedTestCaseUrls;
        List<TestCase> testCases;
        // * fetch top level test case folder items
        // * iterate until all levels fetched
        fetchTestCases(topLevelTestFolder, fetchedTestCaseFolderUrls, fetchedTestCaseUrls, testCases);
    }


    static TestCaseViewResponse fetchTestCaseView(String url) {
        //https://tools.akio.fr/squash/backend/test-case-view/21547?frontEndErrorIsHandled=true
    }

    static void fetchTestCases(String folderUrl,
                               List<String> fetchedTestCaseFolderUrls, List<String> fetchedTestCaseUrls,
                               List<TestCase> testCases) {
        def view = SquashService.fetchFolderView(folderUrl)
        def response = WrapperService.toFolderViewResponse(view)
    }
}
